### ISSUE TITLE
Cannot build 1.99.18-beta under OCaml 4.02.2

### ISSUE THREAD

**Issue by ysalmon** [OCamlPro/ocp-build#88]
Hello,
I cannot build ocp-build 1.99.18-beta. 1.99.17-beta worked fine, I am upgrading from it.
I tried a fresh switch to no avail. It also does not seem to be a dependency problem.
[erreur.zip](https://github.com/OCamlPro/ocp-build/files/966891/erreur.zip)

```
### stderr ###
# [...]
# Error:
# [354.1] '/home/yann/.opam/4.02.2/bin/ocamldep.opt' '-modules' '-I' './_obuild/ocplib-unix' '-I' './libs/ocplib-unix' '-I' './_obuild/ocplib-compat' '-I' './libs/ocplib-compat' '-I' '/home/yann/.opam/4.02.2/lib/ocaml' '-intf' './_obuild/ocplib-unix/_temp/minUnix.mlipp'
# ./_obuild/ocplib-unix/_temp/minUnix.mlipp:
# 
# File "./libs/ocplib-unix/minUnix.mli", line 98, characters 0-2:
# Warning 2: this is not the end of a comment.
# File "./libs/ocplib-unix/minUnix.mli", line 98, characters 1-2:
# Error: Syntax error
# 
# make: *** [build-ocps] Erreur 2
```

**Comment by stedolan** [comment]
I [ran into this bug recently on the multicore OCaml repo](https://github.com/ocamllabs/ocaml-multicore/issues/131), since multicore is currently based on 4.02.2. It turns out that `ocp-pp` supports ocaml 4.02.3 correctly, but is missing a case for 4.02.2.

The `ocp-pp` code does not correctly handle docstrings in 4.02.2, although the [code for 4.02.3](https://github.com/OCamlPro/ocp-build/blob/master/tools/ocp-pp/compat/4.02.3/ocpp_version.ml#L98) seems to work fine in 4.02.2.
